
services:
  db:
    image: mysql:8.0
    platform: linux/amd64 # ARMアーキテクチャの場合、強制的にamd64を指定
    container_name: wordpress_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example_root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: example_password
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    image: wordpress:6.2.2-php8.0-apache
    platform: linux/amd64
    container_name: wordpress
    depends_on:
      - db
    ports:
      - "8080:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: example_password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress:/var/www/html

volumes:
  db_data:
